/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  HackDOSBank,
  HackDOSBankInterface,
} from "../../../Denial of Service/Step One- Hack/HackDOSBank";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_bankAddress",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x60806040526040516101fe3803806101fe833981810160405281019061002591906100ce565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550506100fb565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061009b82610070565b9050919050565b6100ab81610090565b81146100b657600080fd5b50565b6000815190506100c8816100a2565b92915050565b6000602082840312156100e4576100e361006b565b5b60006100f2848285016100b9565b91505092915050565b60f5806101096000396000f3fe608060405260043610601f5760003560e01c8063d0e30db014602a576025565b36602557005b600080fd5b348015603557600080fd5b50603c603e565b005b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663d0e30db0476040518263ffffffff1660e01b81526004016000604051808303818588803b15801560a557600080fd5b505af115801560b8573d6000803e3d6000fd5b505050505056fea2646970667358221220ad7c7dcf47c25d8785c96c47759230272f4eb2c96dcf3c71f9d5456cc8a0d79564736f6c634300080f0033";

type HackDOSBankConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HackDOSBankConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HackDOSBank__factory extends ContractFactory {
  constructor(...args: HackDOSBankConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _bankAddress: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<HackDOSBank> {
    return super.deploy(_bankAddress, overrides || {}) as Promise<HackDOSBank>;
  }
  override getDeployTransaction(
    _bankAddress: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_bankAddress, overrides || {});
  }
  override attach(address: string): HackDOSBank {
    return super.attach(address) as HackDOSBank;
  }
  override connect(signer: Signer): HackDOSBank__factory {
    return super.connect(signer) as HackDOSBank__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HackDOSBankInterface {
    return new utils.Interface(_abi) as HackDOSBankInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HackDOSBank {
    return new Contract(address, _abi, signerOrProvider) as HackDOSBank;
  }
}
