/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  UpgradedDOSBank,
  UpgradedDOSBankInterface,
} from "../../../Denial of Service/Step Two- Defend/UpgradedDOSBank";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "interestAccrued",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "payInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b503373ffffffffffffffffffffffffffffffffffffffff1660808173ffffffffffffffffffffffffffffffffffffffff16815250506080516102de61005d600039600050506102de6000f3fe6080604052600436106100495760003560e01c806263750c1461004e57806327e235e3146100655780633abb7a49146100a2578063a15a211c146100df578063d0e30db0146100f6575b600080fd5b34801561005a57600080fd5b50610063610100565b005b34801561007157600080fd5b5061008c60048036038101906100879190610247565b610102565b604051610099919061028d565b60405180910390f35b3480156100ae57600080fd5b506100c960048036038101906100c49190610247565b61011a565b6040516100d6919061028d565b60405180910390f35b3480156100eb57600080fd5b506100f4610132565b005b6100fe610134565b005b565b60006020528060005260406000206000915090505481565b60016020528060005260406000206000915090505481565b565b670de0b6b3a76400006000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055506002339080600181540180825580915050600190039060005260206000200160009091909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610214826101e9565b9050919050565b61022481610209565b811461022f57600080fd5b50565b6000813590506102418161021b565b92915050565b60006020828403121561025d5761025c6101e4565b5b600061026b84828501610232565b91505092915050565b6000819050919050565b61028781610274565b82525050565b60006020820190506102a2600083018461027e565b9291505056fea2646970667358221220411487add248ab8d26fa18f0f82a9da1a5b5d20f8cbc549116381062cf059bfb64736f6c634300080f0033";

type UpgradedDOSBankConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UpgradedDOSBankConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UpgradedDOSBank__factory extends ContractFactory {
  constructor(...args: UpgradedDOSBankConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<UpgradedDOSBank> {
    return super.deploy(overrides || {}) as Promise<UpgradedDOSBank>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): UpgradedDOSBank {
    return super.attach(address) as UpgradedDOSBank;
  }
  override connect(signer: Signer): UpgradedDOSBank__factory {
    return super.connect(signer) as UpgradedDOSBank__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UpgradedDOSBankInterface {
    return new utils.Interface(_abi) as UpgradedDOSBankInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UpgradedDOSBank {
    return new Contract(address, _abi, signerOrProvider) as UpgradedDOSBank;
  }
}
