/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Bank__factory } from "./Bank__factory";
export { UpgradedBank__factory } from "./UpgradedBank__factory";
