/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DOSBank__factory } from "./DOSBank__factory";
export { UpgradedDOSBank__factory } from "./UpgradedDOSBank__factory";
