/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { HackBank, HackBankInterface } from "../../Hack/HackBank";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_bankAddress",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "hackContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405260405161034a38038061034a833981810160405281019061002591906100ce565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550506100fb565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061009b82610070565b9050919050565b6100ab81610090565b81146100b657600080fd5b50565b6000815190506100c8816100a2565b92915050565b6000602082840312156100e4576100e361006b565b5b60006100f2848285016100b9565b91505092915050565b6102408061010a6000396000f3fe6080604052600436106100225760003560e01c80637ca2474e146100f0576100eb565b366100eb5760008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163111156100e95760008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16633ccfd60b6040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156100d057600080fd5b505af11580156100e4573d6000803e3d6000fd5b505050505b005b600080fd5b3480156100fc57600080fd5b50610105610107565b005b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663d0e30db0476040518263ffffffff1660e01b81526004016000604051808303818588803b15801561016f57600080fd5b505af1158015610183573d6000803e3d6000fd5b505050505060008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16633ccfd60b6040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156101f057600080fd5b505af1158015610204573d6000803e3d6000fd5b5050505056fea2646970667358221220aba603863f018ddbe74df7573f59409c5accc8c927ccaecf4b15fefeb35c833f64736f6c634300080f0033";

type HackBankConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HackBankConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HackBank__factory extends ContractFactory {
  constructor(...args: HackBankConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _bankAddress: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<HackBank> {
    return super.deploy(_bankAddress, overrides || {}) as Promise<HackBank>;
  }
  override getDeployTransaction(
    _bankAddress: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_bankAddress, overrides || {});
  }
  override attach(address: string): HackBank {
    return super.attach(address) as HackBank;
  }
  override connect(signer: Signer): HackBank__factory {
    return super.connect(signer) as HackBank__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HackBankInterface {
    return new utils.Interface(_abi) as HackBankInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HackBank {
    return new Contract(address, _abi, signerOrProvider) as HackBank;
  }
}
