/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Bank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Bank__factory>;
    getContractFactory(
      name: "HackBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HackBank__factory>;
    getContractFactory(
      name: "VulerableBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VulerableBank__factory>;
    getContractFactory(
      name: "UpgradedBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradedBank__factory>;

    getContractAt(
      name: "Bank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Bank>;
    getContractAt(
      name: "HackBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.HackBank>;
    getContractAt(
      name: "VulerableBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VulerableBank>;
    getContractAt(
      name: "UpgradedBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradedBank>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
