/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DOSKing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DOSKing__factory>;
    getContractFactory(
      name: "HackDOSKing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HackDOSKing__factory>;
    getContractFactory(
      name: "UpgradedDOSKing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradedDOSKing__factory>;
    getContractFactory(
      name: "HackReentrancyBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HackReentrancyBank__factory>;
    getContractFactory(
      name: "ReentrancyBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyBank__factory>;
    getContractFactory(
      name: "UpgradedReenterencyBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradedReenterencyBank__factory>;

    getContractAt(
      name: "DOSKing",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DOSKing>;
    getContractAt(
      name: "HackDOSKing",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.HackDOSKing>;
    getContractAt(
      name: "UpgradedDOSKing",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradedDOSKing>;
    getContractAt(
      name: "HackReentrancyBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.HackReentrancyBank>;
    getContractAt(
      name: "ReentrancyBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyBank>;
    getContractAt(
      name: "UpgradedReenterencyBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradedReenterencyBank>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
