/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DOSBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DOSBank__factory>;
    getContractFactory(
      name: "HackDOSBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HackDOSBank__factory>;
    getContractFactory(
      name: "UpgradedDOSBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradedDOSBank__factory>;
    getContractFactory(
      name: "HackReenterencyBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HackReenterencyBank__factory>;
    getContractFactory(
      name: "ReenterencyBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReenterencyBank__factory>;
    getContractFactory(
      name: "UpgradedReenterencyBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradedReenterencyBank__factory>;

    getContractAt(
      name: "DOSBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DOSBank>;
    getContractAt(
      name: "HackDOSBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.HackDOSBank>;
    getContractAt(
      name: "UpgradedDOSBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradedDOSBank>;
    getContractAt(
      name: "HackReenterencyBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.HackReenterencyBank>;
    getContractAt(
      name: "ReenterencyBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ReenterencyBank>;
    getContractAt(
      name: "UpgradedReenterencyBank",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradedReenterencyBank>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
